"""Init

Revision ID: 639f9f03f6db
Revises:
Create Date: 2025-11-05 14:07:34.924678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "639f9f03f6db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "City",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("additional_info", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_City_id"), "City", ["id"], unique=False)
    op.create_index(op.f("ix_City_name"), "City", ["name"], unique=True)
    op.create_table(
        "Temperature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("date_time", sa.String(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Temperature_city_id"), "Temperature", ["city_id"], unique=False
    )
    op.create_index(
        op.f("ix_Temperature_date_time"), "Temperature", ["date_time"], unique=False
    )
    op.create_index(op.f("ix_Temperature_id"), "Temperature", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Temperature_id"), table_name="Temperature")
    op.drop_index(op.f("ix_Temperature_date_time"), table_name="Temperature")
    op.drop_index(op.f("ix_Temperature_city_id"), table_name="Temperature")
    op.drop_table("Temperature")
    op.drop_index(op.f("ix_City_name"), table_name="City")
    op.drop_index(op.f("ix_City_id"), table_name="City")
    op.drop_table("City")
    # ### end Alembic commands ###
